---
version: 2
# https.//docs.readthedocs.io/en/stable/config-file/v2.html

python:
  version: "3.6"
  install:
    - method: pip
      path: .
      extra_requirements:
        - documentation
    - method: setuptools
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py