from os import PathLike


class File:

    def __init__(self, path: str, easy: bool = False) -> None: ...

    def save(self) -> None: ...

    def __setitem__(self, key: str, value: str) -> None: ...

    def __getitem__(self, key: str) -> str: ...
