---
name: Python package checks

on: # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - master

jobs:
  style:
    name: Checks code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Check style
        run: |
          tox -e style

  typing:
    name: Checks types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Checks typping
        run: |
          tox -e typing

  unittests:
    name: Runs unittests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    needs:
      - style
      - typing
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.versions }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.versions }}
      - name: Install tox
        run: pip install tox
      - name: Test with pytest
        run: |
          tox -e unittests

  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    needs:
      - style
      - typing
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Build documentation
        run: |
          tox -e documentation
      - name: Archive documentation
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: build/sphinx/html/

  execute:
    name: Check terminal program
    runs-on: ubuntu-latest
    needs:
      - unittests
    strategy:
      fail-fast: false
      matrix:
        versions: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.versions }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.versions }}
      - name: Install tox
        run: pip install tox
      - name: Run console program
        run: |
          tox -e execute

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs:
      - execute
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Run console program
        run: |
          tox -e integration

  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    needs:
      - execute
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: MegaLinter
        id: ml
        uses: megalinter/megalinter@v5
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log

  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "python"
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  CI-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Upgrade version
        id: vars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RC="$(sed 's/\s*self\._rc\s*=\s*\([0-9]*\)\s/\1/gp;d' ytrss/core/version.py)"
          NEW_RC=$(( RC + 1 ))

          sed -i "s/self\._rc = [0-9]*/self._rc = ${NEW_RC}/" ytrss/core/version.py

          GIT_TAG="$(python ./setup.py --version)"

          # spellcheck disable=SC2001
          echo ::set-output name="git_tag::${GIT_TAG}"
      - name: Commit massage
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          export GIT_TAG=${{ steps.vars.outputs.git_tag }}
          git commit -a -m "Upgrade to ${GIT_TAG} version"
          git tag v${GIT_TAG} -a -m "Upgrade to ${GIT_TAG} version"
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: ytrss/core/version.py

  CI-upgrade-with-base:
    runs-on: ubuntu-latest
    needs: CI-upgrade
    steps:
      - uses: actions/checkout@v1
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: version
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Build distribution
        run: python setup.py sdist
      - name: Publish package
        run: |
          mv version ytrss/core/version.py
          python ./setup.py --version
          cat ytrss/core/version.py

  CI-upgrade-without-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Build distribution
        run: python setup.py sdist
      - name: Publish package
        run: |
          python ./setup.py --version
          cat ytrss/core/version.py
          
