ame: Package upgrade

on:
  push:
    branches:
    - master
    # TODO: change package name
    paths-ignore:
    - 'template-python-package/__init_.py'

jobs:
  CI-upgrade:
    # TODO: delete to turn on
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Upgrade version
      id: vars
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # TODO: change package name
      run: |
        echo ${GITHUB_TOKEN}
        export VERSION=$(python ./setup.py --version)
        export MIJOR=$(echo $VERSION | sed 's/\([0-9]*\)\.[0-9]*\.[0-9]*/\1/')
        export MINOR=$(echo $VERSION | sed 's/[0-9]*\.\([0-9]*\)\.[0-9]*/\1/')
        export PATCH=$(echo $VERSION | sed 's/[0-9]*\.[0-9]*\.\([0-9]*\)/\1/')
        export GIT_TAG="$MIJOR.$MINOR."$(( PATCH + 1 ))
        sed -i "s/return \"[0-9\.]*\"/return \"${GIT_TAG}\"/" template-python-package/__init__.py
        echo ::set-output name=git_tag::${GIT_TAG}
    - name: Commit massage
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        export GIT_TAG=${{ steps.vars.outputs.git_tag }}
        git commit -a -m "Upgrade to ${GIT_TAG} version"
        git tag v${GIT_TAG} -a -m "Upgrade to ${GIT_TAG} version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build distribution
      run: python setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}