---
name: Package upgrade

on:
  push:
    branches:
      - master
    paths-ignore:
      - "ytrss/__init_.py"

jobs:
  CI-upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade version
        id: vars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: change package name
        run: |
          echo "${GITHUB_TOKEN}"
          VERSION="$(python ./setup.py --version)"
          # shellcheck disable=SC2001
          MAJOR="$(echo "${VERSION}" | sed 's/\([0-9]*\)\.[0-9]*\.[0-9]*/\1/')"
          # shellcheck disable=SC2001
          MINOR="$(echo "${VERSION}" | sed 's/[0-9]*\.\([0-9]*\)\.[0-9]*/\1/')"
          # shellcheck disable=SC2001
          PATCH="$(echo "${VERSION}" | sed 's/[0-9]*\.[0-9]*\.\([0-9]*\)/\1/')"
          GIT_TAG="$MAJOR.$MINOR."$(( PATCH + 1 ))
          # spellcheck disable=SC2001
          sed -i "s/return \"[0-9\.]*\"/return \"${GIT_TAG}\"/" ytrss/__init__.py
          echo ::set-output name="git_tag::${GIT_TAG}"
      - name: Commit massage
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          export GIT_TAG=${{ steps.vars.outputs.git_tag }}
          git commit -a -m "Upgrade to ${GIT_TAG} version"
          git tag v${GIT_TAG} -a -m "Upgrade to ${GIT_TAG} version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build distribution
        run: python setup.py sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
